### ISSUE TITLE
Fundation lastest version breakpoints

### ISSUE THREAD

**Issue by s-leger** [smadsen/theme_foundation#1]
Hi,
Last fundation handle 5 breakoints. (adds extra large screen) Any plans to support this ?
Name for generic class map for this new one ?

**Comment by kaystrobach** [comment]
currently we concentrate on the 90% which are solved with the current approach.

Additionally you can define any css breakpoint you want. But we also want to ensure, that you can switch between themes without loosing your content.

You can still manipulate the classmap, so that your special theme can support as many breakpoints as you want either mapped by desktop mobile etc. or by custom ones, but be aware, that switching themes may fail horrible then :(

**Comment by kaystrobach** [comment]
FYI: @smadsen
